"""add barber_absence table

Revision ID: 2e10aacb67d7
Revises: af76e5622171
Create Date: 2026-07-27 20:12:28.600282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e10aacb67d7'
down_revision = 'af76e5622171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barber_absence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barber_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('unavailable_from', sa.Time(), nullable=True),
    sa.Column('unavailable_to', sa.Time(), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barber_id'], ['barber.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barber_absence')
    # ### end Alembic commands ###
